### ISSUE TITLE
Error with spark_connect()

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/Discussion#46]
@uc-cfss/fa17 If you run the command

```r
library(sparklyr)
sc <- spark_connect(master = "local")
```

And receive an error similar to this:

```
Error in force(code) : Failed while connecting to sparklyr to port (8880) for sessionid (7199): Gateway in port (8880) did not respond. Path: C:\Users\HP\AppData\Local\rstudio\spark\Cache\spark-2.0.0-bin-hadoop2.7\bin\spark-submit2.cmd Parameters: --class, sparklyr.Backend, "C:\Users\HP\Documents\R\win-library\3.3\sparklyr\java\sparklyr-2.0-2.11.jar", 8880, 7199 ---- Output Log ---- '"java"' is not recognized as an internal or external command, operable program or batch file. ---- Error Log ----
```

This occurred for several students last year. A couple things worked for them.

## Install `sparklyr` directly from GitHub

```r
devtools::install_github("rstudio/sparklyr", dependencies =TRUE)
spark_install(version = "1.6.2")
```

This ensures you install the most recent version of `sparklyr`

## Reintall Java 1.8

Spark doesn't always play nicely with Java, a base computer programming language on which many applications are run. Ensuring you have Java 1.8 installed seemed to help some students.

### Instructions for Windows

[See here](http://www.herongyang.com/JVM/JDK-180-Windows-Download-Installation.html.html)

#### 1. Install Homebrew

If you have not already installed this for another class, install [Homebrew](https://brew.sh). You do this by opening terminal and running the following command:

```Shell
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

Hit enter, and then enter and your computer password when prompted. Once installed, enter this command in terminal:

#### 2. Install Java JDK

```Shell
brew cask install java
```

Enter password again when prompted. This will install the Java JDK. Next restart R, and you should be good to go.

**Comment by arthurzeyangyu** [comment]
Thanks!

**Comment by fushu18** [comment]
Hi Dr. Soltoff,

I still get the error. I have installed java 9, as suggested online, but it doesn’t work. And I follow your instructions in the previous email. Now I got new errors. The spark_connect function works now but I cannot copy_to. The errors are shown as follows.

I use a MacBook Pro (Retina, 13-inch, Early 2015), I don’t know whether it is a unique problem of my own Mac. Plz help me!

Thanks!

Shu

——————————— R Code & Errors ——————————————

> library(sparklyr)
> options(sparklyr.java9 = TRUE)
> sc <- spark_connect(master = "local")
* Using Spark: 2.1.0
Spark version 2.1 detected. Will call latest Sparkling Water version 2.1.16

> library(titanic)
> (titanic_tbl <- copy_to(sc, titanic::titanic_train, "titanic", overwrite = TRUE))
Error: java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionState':
at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$reflect(SparkSession.scala:981)
at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:110)
at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:109)
at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:878)
at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:878)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:878)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at sparklyr.Invoke$.invoke(invoke.scala:102)
at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
at sparklyr.StreamHandler$.read(stream.scala:62)
at sparklyr.BackendHandler.channelRead0(handler.scala:52)
at sparklyr.BackendHandler.channelRead0(handler.scala:14)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$reflect(SparkSession.scala:978)
... 44 more
Caused by: java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveExternalCatalog':
at org.apache.spark.sql.internal.SharedState$.org$apache$spark$sql$internal$SharedState$$reflect(SharedState.scala:169)
at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:86)
at org.apache.spark.sql.SparkSession$$anonfun$sharedState$1.apply(SparkSession.scala:101)
at org.apache.spark.sql.SparkSession$$anonfun$sharedState$1.apply(SparkSession.scala:101)
at scala.Option.getOrElse(Option.scala:121)
at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:101)
at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:100)
at org.apache.spark.sql.internal.SessionState.<init>(SessionState.scala:157)
at org.apache.spark.sql.hive.HiveSessionState.<init>(HiveSessionState.scala:32)
... 49 more
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
at org.apache.spark.sql.internal.SharedState$.org$apache$spark$sql$internal$SharedState$$reflect(SharedState.scala:166)
... 57 more
Caused by: java.lang.ClassNotFoundException: java.lang.NoClassDefFoundError: org/apache/hadoop/hive/conf/HiveConf when creating Hive client using classpath: file:/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-2.1-2.11.jar, file:/Users/ShuFu/.ivy2/jars/ai.h2o_sparkling-water-core_2.11-2.1.16.jar, file:/Users/ShuFu/.ivy2/jars/ai.h2o_sparkling-water-ml_2.11-2.1.16.jar, file:/Users/ShuFu/.ivy2/jars/ai.h2o_sparkling-water-repl_2.11-2.1.16.jar, file:/Users/ShuFu/.ivy2/jars/no.priv.garshol.duke_duke-1.2.jar, file:/Users/ShuFu/.ivy2/jars/ai.h2o_h2o-genmodel-3.14.0.7.jar, file:/Users/ShuFu/.ivy2/jars/ai.h2o_h2o-core-3.14.0.7.jar, file:/Users/ShuFu/.ivy2/jars/ai.h2o_h2o-algos-3.14.0.7.jar, file:/Users/ShuFu/.ivy2/jars/ai.h2o_h2o-web-3.14.0.7.jar, file:/Users/ShuFu/.ivy2/jars/ai.h2o_h2o-ext-xgboost-3.14.0.7.jar, file:/Users/ShuFu/.ivy2/jars/ai.h2o_h2o-genmodel-ext-xgboost-3.14.0.7.jar, file:/Users/ShuFu/.ivy2/jars/ai.h2o_h2o-scala_2.11-3.14.0.7.jar, file:/Us... <truncated>
>



On 6 Nov 2017, at 8:27 PM, Benjamin Soltoff <notifications@github.com<mailto:notifications@github.com>> wrote:


@uc-cfss/fa17<https://github.com/orgs/uc-cfss/teams/fa17> If you run the command

library(sparklyr)
sc <- spark_connect(master = "local")

And receive an error similar to this:

Error in force(code) : Failed while connecting to sparklyr to port (8880) for sessionid (7199): Gateway in port (8880) did not respond. Path: C:\Users\HP\AppData\Local\rstudio\spark\Cache\spark-2.0.0-bin-hadoop2.7\bin\spark-submit2.cmd Parameters: --class, sparklyr.Backend, "C:\Users\HP\Documents\R\win-library\3.3\sparklyr\java\sparklyr-2.0-2.11.jar", 8880, 7199 ---- Output Log ---- '"java"' is not recognized as an internal or external command, operable program or batch file. ---- Error Log ----


This occurred for several students last year. A couple things worked for them.

Install sparklyr directly from GitHub

devtools::install_github("rstudio/sparklyr", dependencies =TRUE)
spark_install(version = "1.6.2")

This ensures you install the most recent version of sparklyr

Reintall Java 1.8

Spark doesn't always play nicely with Java, a base computer programming language on which many applications are run. Ensuring you have Java 1.8 installed seemed to help some students.

Instructions for Windows

See here<http://www.herongyang.com/JVM/JDK-180-Windows-Download-Installation.html.html>

Instructions for Mac
1. Install Homebrew

If you have not already installed this for another class, install Homebrew<https://brew.sh/>. You do this by opening terminal and running the following command:

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Hit enter, and then enter and your computer password when prompted. Once installed, enter this command in terminal:

2. Install Java JDK

brew cask install java

Enter password again when prompted. This will install the Java JDK. Next restart R, and you should be good to go.

**Comment by bensoltoff** [comment]
@fushu18 did you restart R after you installed Java? Make sure to restart R by using "Session > Restart R" in the dropdown menu in RStudio, then try `spark_connect()`

**Comment by yucheny** [comment]
Dear Dr. Soltoff,

I followed your instruction to install Homebrew and Java JDK, but I still got an error message. What should I do?

Thanks,
Yuchen

> library(sparklyr)
Warning message:
package ‘sparklyr’ was built under R version 3.4.2 
> sc <- spark_connect(master = "local")
> * Using Spark: 2.1.0
> Error in validate_java_version_line(master, version) : 
>  Java 9 is currently unsupported in Spark distributions unless you manually install Hadoop 2.8 and manually configure Spark. Please consider uninstalling Java 9 and reinstalling Java 8. To override this failure set 'options(sparklyr.java9 = TRUE)'.

**Comment by fushu18** [comment]
Yup. I restarted it. Still doesn’t work. Well, I guess this error may very well be a special case. We can talk in tomorrow’s lab. Thanks!

--
Shu Fu

PhD Student
Department of Political Science
The University of Chicago

Cell: +1 (312) 256 5123
Email: fushu@uchicago.edu<mailto:fushu@uchicago.edu>


On 7 Nov 2017, at 10:13 AM, Benjamin Soltoff <notifications@github.com<mailto:notifications@github.com>> wrote:


@fushu18<https://github.com/fushu18> did you restart R after you installed Java? Make sure to restart R by using "Session > Restart R" in the dropdown menu in RStudio, then try spark_connect()

**Comment by zczhu1995** [comment]
I've got the same problem!


> library(sparklyr)
> spark_install(version = "2.1.0")
Spark 2.1.0 for Hadoop 2.7 or later already installed.
> sc <- spark_connect(master = "local")
* Using Spark: 2.1.0
Error in validate_java_version_line(master, version) : 
  Java 9 is currently unsupported in Spark distributions unless you manually install Hadoop 2.8 and manually configure Spark. Please consider uninstalling Java 9 and reinstalling Java 8. To override this failure set 'options(sparklyr.java9 = TRUE)'.


And after I set 'options(sparklyr.java9 = TRUE)', it still doesn't work.
